---
title: "R Notebook"
output: html_notebook
---


```{r}
library(macpan2)
library(shellpipes)
rpcall("calibrate.Rout calibrate.R timevar_spec.rds seroprevdata.rds fitsero.rds params.rda")
library(conflicted)
library(tidyverse)
library(dplyr)
library(ggthemes)
library(broom.mixed)
library(lubridate)
library(ggplot2)
library(RColorBrewer)
library(tidyr)
library(zoo)
library(cowplot)
library(patchwork)
library(fuzzyjoin)
library(scales)

if (packageVersion("macpan2") < "2.5.0") {
  stop(
      "Please install a new version of macpan2\n"
    , "https://canmod.github.io/macpan2/#installation"
  )
}

set.seed(2025)
options(macpan2_log_dir = ".")
loadEnvironments()
```

```{r warning=FALSE, message=FALSE}
offset0 <- 150
prior_range = list(
    kappa2 = c(0.85, 0.95)
  , kappa3 = c(0.2, 0.4)
  , gamma_a = c(1/11, 1/8)
  , gamma_i = c(1/8, 1/6)
  , sigma = c(1/4, 1/2)
)
spline_beta = TRUE

timevar_spec <- readRDS("timevar_spec.rds")

seroprevdata <- readRDS("seroprevdata.rds")
fitserodata <- readRDS("fitsero.rds")
time_steps = max(seroprevdata$time)
upper_plot_time = 300 #time_steps

## SW: i'm winging this ...
fitserodata = (seroprevdata 
  |> dplyr::mutate(value = timevar_spec$default$N * (value - dplyr::lag(value)) / 7)
  |> dplyr::mutate(matrix = "inc")
)

if (spline_beta) {
  basis_cols = 5
  basis_rows = time_steps
  X = splines::ns(1:basis_rows
    , basis_cols
    , intercept = TRUE
    , Boundary.knots = c(offset0, basis_rows)
  )
  timevar_spec = mp_tmb_insert_glm_timevar(timevar_spec
    , parameter_name = "beta"
    , design_matrix = X
    , timevar_coef = rep(0, basis_cols)
    , link_function = mp_log
  )
}
get_prior = function(trans) function(rng) {
  mp_normal(
      (trans(rng[1]) + trans(rng[2])) / 2
    , log((trans(rng[2]) - trans(rng[1])) / (2 * 1.96))
  )
}
priors = list(
      log_beta = mp_normal(log(0.25), log(1))
    , time_var_beta = mp_normal(0, log(1))
    , log_gamma_a = get_prior(log)(prior_range$gamma_a)
    , log_gamma_i = get_prior(log)(prior_range$gamma_i)
    , logit_kappa2 = get_prior(qlogis)(prior_range$kappa2)
    , logit_kappa3 = get_prior(qlogis)(prior_range$kappa3)
    , log_sigma = get_prior(log)(prior_range$sigma)
)
calibrator = mp_tmb_calibrator(
    spec = timevar_spec |> mp_rk4() 
  , data = (seroprevdata 
      |> select(-date) 
      |> dplyr::filter(matrix == "serop") 
      |> dplyr::mutate(matrix = "logit_serop", value = qlogis(value))
  )
  , time = mp_sim_bounds(1, time_steps)
  , traj = list(logit_serop = mp_normal(sd = mp_fit(1)))
  , par = priors
  , outputs = c("log_beta_thing", "log_inc", "logit_serop")
)
mp_optimize(calibrator)

sims = (calibrator
  |> mp_trajectory_sd(conf.int = TRUE, back_transform = TRUE)
  |> dplyr::filter(time >= offset0)
)

lim_dat = \(x) dplyr::filter(x, time <= upper_plot_time)
print(ggplot()
 + geom_point(aes(time, value), data = lim_dat(seroprevdata))
 + geom_point(aes(time, value), data = lim_dat(fitserodata))
 + geom_line(aes(time, value), linewidth = 1, data = lim_dat(sims))
 + geom_ribbon(aes(x = time, ymin = conf.low, ymax = conf.high), alpha = 0.4, data = lim_dat(sims))
 + facet_wrap(~matrix, scales = "free", ncol = 1)
 + scale_y_continuous(name = "")
 + scale_x_continuous(limits = c(offset0, upper_plot_time))
 + theme_bw()
)

print(calibrator
  |> mp_optimized_spec("modified")
  |> mp_simulator(time_steps, outputs = mp_state_vars(timevar_spec))
  |> mp_trajectory()
  |> lim_dat()
  |> ggplot()
  + aes(time, value)
  + geom_line()
  + facet_wrap(~matrix, scales = "free")
  #+ scale_x_continuous(limits = c(offset0, time_steps))
  + theme_bw()
)

remade_vax_data = list(
  double_vac = data.frame(
      time = timevar_spec$integers$double_vac_changepoints
    , value = timevar_spec$default$double_vac_values
  ),
  booster_shot = data.frame(
      time = timevar_spec$integers$booster_vac_changepoints
    , value = timevar_spec$default$booster_vac_values
  )
) |> bind_rows(.id = "matrix")

simdat <- calibrator |>
  mp_optimized_spec("modified") |>
  mp_simulator(time_steps, outputs = c("double_vac", "booster_shot", "E1","E2","E3","A1","A2","A3","I1","I2","I3","R1","R2","R3")) |> 
  mp_trajectory() |>
  lim_dat() |>
  dplyr::filter(time >= 150)

ggplot(simdat, aes(time, value)) +
  geom_line() +
  facet_wrap(~matrix, scales = "free") +
  theme_bw()

```

```{r fig.height=10, fig.width=20}
simdat <- simdat |>
  dplyr::mutate(
    matrix = recode(
      matrix,
      "double_vac" = "Double Vaccination",
      "booster_shot" = "Booster Shot"
    )
  )

simdat <- simdat |>
  dplyr::mutate(date = as.Date("2021-12-15") + time -150) |>
  # reverse to make double come before booster
  dplyr::mutate(matrix = factor(matrix, levels = c("Double Vaccination","Booster Shot")))

gg <- ggplot(simdat, aes(x = date, y = value, color = matrix)) +
  geom_line(linewidth = 1) +
  geom_point(size = 5, alpha = 0.8) +
  scale_color_manual(
    values = c(
      "Double Vaccination" = "#0072B2",  # blue
      "Booster Shot" = "#D55E00"         # orange
    ),
    name = NULL
  ) +
  facet_wrap(~ matrix, scales = "free_y", nrow = 1) +
  scale_x_date(
    date_breaks = "2 weeks",
    date_labels = "%b %d",
    expand = c(0.01, 0.01)
  ) +
  scale_y_continuous(
    labels = comma_format(),
    expand = c(0.01, 0.01)
  ) +
  labs(
    title = "Daily Vaccination Uptake",
    x = "Date",
    y = "Number of Individuals"
  ) +
  theme_clean(base_size = 12) +
  theme(
    plot.title = element_text(face = "bold", size = 25, hjust = 0.5),
    plot.subtitle = element_text(size = 25, hjust = 0.5),
    axis.title = element_text(size = 25),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 25),
    axis.text.y = element_text(size = 25),
    strip.text = element_text(size = 25, face = "bold"),
    legend.position = "bottom",
    legend.text = element_text(size = 25),
    plot.background = element_blank(),
    legend.background = element_blank()
  )

print(gg)
```

```{r}
simdat
start_date <- as.Date("2021-12-15") - offset0
last_date <-"2022-05-22"

seroprevdata <- rdsRead("seroprevdata.rds")
time_steps = max(seroprevdata$time)
upper_plot_time = 300

seroprevdata <- seroprevdata %>%
  complete(date = seq.Date(
    from = as.Date("2021-12-15"),
    to   = max(date),
    by   = "1 day"
))

seroprevdata <- (seroprevdata
	|> select(c("date","value"))
	|> dplyr::filter(date >= as.Date("2021-12-15") & date <= as.Date("2022-05-22"))
)

seroprev_plot <- (ggplot() +
  geom_point(
    data = seroprevdata,
    aes(x = date, y = value, color = "Seroprevalence"),
    size = 2.5,
    show.legend = TRUE
  ) +
  scale_x_date(
    #expand = c(0, 0),
    date_breaks = "2 week",
    date_labels = "%b %d"
  ) +
  labs(
    x = "Date (Dec 15, 2021 - May 22, 2022)",
    y = "Seroprevalence Estimate (%)",
    title = "Seroprevalence Estimate (%)"
  ) +
  scale_color_manual(
    name = NULL,
    values = c("Seroprevalence" = "black")
    ) +
  theme_clean() +
  theme(
    axis.text.x = element_text(size = 14, angle = 45, hjust = 0.85),
    axis.title.x = element_text(size = 16, color = "black", face = "bold"),
    axis.text.y = element_text(size = 14),
    axis.title.y = element_text(size = 16, color = "black", face = "bold"),
    plot.title = element_text(size = 16, color = "black", hjust = 0.5),
    strip.text = element_text(size = 14, color = "black"),
    legend.title = element_blank(),
    legend.text = element_text(size = 16),
    legend.background = element_rect(color = NA),
    legend.margin = margin(0, 0, 0, 0),
    plot.background = element_blank(),
    legend.position = c(0.2, 0.8)
  ) )
```

```{r}
# load reported data
reported_cases <- read.csv("~/Documents/MUN/Thesis Samples/quantifying_omicron_burden_in_NL/data/serop_avgcase_data.csv")
reported_cases$date <- as.Date(reported_cases$date, format = "%Y-%m-%d")

reported_cases <- reported_cases |>
        dplyr::filter(date <= as.Date("2022-05-22"))

# drop all NAs
reported_cases <- reported_cases |>
  drop_na()

reported_cases <- (ggplot(reported_cases, aes(x = date)) +
  geom_point( aes(y = cases, color = "Reported Cases"),size = 2.5) +
  scale_x_date(
    #expand = c(0, 0),
    date_breaks = "2 week",
    date_labels = "%b %d"
  ) +
  labs(
    x = "Date (Dec 15, 2021 - May 22, 2022)",
    y = "Daily reported cases",
    title = "Smoothed Daily Reported Cases"
  ) +
  scale_color_manual(
    name = NULL,
    values = c("Reported Cases" = "black")
    ) +
  theme_clean() +
  theme(
    axis.text.x = element_text(size = 14, angle = 45, hjust = 0.85),
    axis.title.x = element_text(size = 16, color = "black", face = "bold"),
    axis.text.y = element_text(size = 16),
    axis.title.y = element_text(size = 16, color = "black", face = "bold"),
    plot.title = element_text(size = 16, color = "black", hjust = 0.5),
    strip.text = element_text(size = 14, color = "black"),
    legend.title = element_blank(),
    legend.text = element_text(size = 16),
    legend.background = element_rect(color = NA),
    legend.margin = margin(0, 0, 0, 0),
    plot.background = element_blank(),
    legend.position = c(0.8, 0.8)
  ))
```

```{r warning=FALSE, message=FALSE, fig.height=7, fig.width=18}
final_plot <- plot_grid(
  reported_cases, 
  seroprev_plot,
  labels = c("R","S"),
  nrow = 1,
  align = "v",      # align plots vertically for horizontal layout
  axis = "tb",      # align top and bottom axes
  rel_widths = c(1, 1) # adjust widths if plots differ in size
)

final_plot
```



